
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: turcoWeb_development
  pool: 5
  username: root
  password: 123456
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: turcoWeb_test
  pool: 5
  username: root
  password: 123456
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: turcoWeb_production
  pool: 5
  username: root
  password: 123456
  host: localhost
