class FloatureTerminator < ActiveRecord::Migration
  def self.up
    change_column(:apportionments           , :rate        , :decimal, :precision => 10, :scale => 4)
    change_column(:csts                     , :value       , :decimal, :precision => 10, :scale => 4)
    change_column(:order_items              , :quantity    , :decimal, :precision => 10, :scale => 4)
    change_column(:order_items              , :unit_value  , :decimal, :precision => 10, :scale => 2)
    change_column(:order_items              , :total_value , :decimal, :precision => 10, :scale => 2)
    change_column(:orders                   , :commission  , :decimal, :precision => 10, :scale => 4)
    change_column(:orders                   , :freight     , :decimal, :precision => 10, :scale => 4)
    change_column(:products                 , :weight      , :decimal, :precision => 10, :scale => 3)
    change_column(:products                 , :ipi         , :decimal, :precision => 10, :scale => 4)
    change_column(:products                 , :price       , :decimal, :precision => 10, :scale => 2)
    change_column(:products                 , :cost        , :decimal, :precision => 10, :scale => 2)
    change_column(:products                 , :liquid_price, :decimal, :precision => 10, :scale => 2)
    change_column(:products                 , :pis         , :decimal, :precision => 10, :scale => 4)
    change_column(:products                 , :cofins      , :decimal, :precision => 10, :scale => 4)
    change_column(:receivable_billings      , :value       , :decimal, :precision => 10, :scale => 2)
    change_column(:receivable_billings      , :fine        , :decimal, :precision => 10, :scale => 4)
    change_column(:receivable_billings      , :rate        , :decimal, :precision => 10, :scale => 4)
    change_column(:receivable_billings      , :discount    , :decimal, :precision => 10, :scale => 2)
    change_column(:receivable_billings      , :total       , :decimal, :precision => 10, :scale => 2)
    change_column(:receivable_cost_divisions, :value       , :decimal, :precision => 10, :scale => 2)
    change_column(:receivables              , :rate        , :decimal, :precision => 10, :scale => 4)
    change_column(:receivables              , :fine        , :decimal, :precision => 10, :scale => 4)
    change_column(:seller_credit_accounts   , :credit      , :decimal, :precision => 10, :scale => 2)
    change_column(:seller_credit_accounts   , :debit       , :decimal, :precision => 10, :scale => 2)
  end

  def self.down
    change_column(:apportionments           , :rate        , :float)
    change_column(:csts                     , :value       , :float)
    change_column(:order_items              , :quantity    , :float)
    change_column(:order_items              , :unit_value  , :float)
    change_column(:order_items              , :total_value , :float)
    change_column(:orders                   , :commission  , :float)
    change_column(:orders                   , :freight     , :float)
    change_column(:products                 , :weight      , :float)
    change_column(:products                 , :ipi         , :float)
    change_column(:products                 , :price       , :float)
    change_column(:products                 , :cost        , :float)
    change_column(:products                 , :liquid_price, :float)
    change_column(:products                 , :pis         , :float)
    change_column(:products                 , :cofins      , :float)
    change_column(:receivable_billings      , :value       , :float)
    change_column(:receivable_billings      , :fine        , :float)
    change_column(:receivable_billings      , :rate        , :float)
    change_column(:receivable_billings      , :discount    , :float)
    change_column(:receivable_billings      , :total       , :float)
    change_column(:receivable_cost_divisions, :value       , :float)
    change_column(:receivables              , :rate        , :float)
    change_column(:receivables              , :fine        , :float)
    change_column(:seller_credit_accounts   , :credit      , :float)
    change_column(:seller_credit_accounts   , :debit       , :float)
  end
end
